// Workout attendance manager: choose an existing workout, paste attendance, and show only no-shows who have gear.
(function(){
  const ATTENDANCE_KEY='combatEquipmentAttendanceV2';
  const PHONE_KEY='combatEquipmentPhonesV1';
  const clean=s=>String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').replace(/[*.]/g,'').replace(/^\s*\d+[.)]?\s*/,'').replace(/^\s*[⁠•\-–—]+\s*/,'').trim();
  const norm=s=>clean(s).replace(/\s+/g,' ').toLocaleLowerCase('he');
  let selectedWorkout='current';
  function historyItems(){try{return typeof histories==='function'?histories():JSON.parse(localStorage.getItem('combatEquipmentHistoryV1')||'[]')}catch{return []}}
  function workoutOptions(){const h=historyItems();return [{key:'current',label:'האימון הנוכחי',equipment:Array.isArray(state?.equipment)?state.equipment:[]}].concat(h.map((x,i)=>({key:'history-'+i,label:x?.date||`אימון ${i+1}`,equipment:Array.isArray(x?.equipment)?x.equipment:[]})))}
  function selectedInfo(){const opts=workoutOptions();return opts.find(x=>x.key===selectedWorkout)||opts[0]||{key:'current',label:'האימון הנוכחי',equipment:[]}}
  function allData(){try{return JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'{}')}catch{return {}}}
  function getSelected(){const d=allData()[selectedWorkout];return d&&Array.isArray(d.attending)&&Array.isArray(d.absent)?d:{attending:[],absent:[],raw:''}}
  function saveSelected(data){const all=allData();all[selectedWorkout]=data;localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));renderAttendance();checkAssignedNoShows()}
  function parseList(text){const lines=String(text||'').split(/\r?\n/);let mode='';const attending=[],absent=[];for(const raw of lines){const line=clean(raw);if(!line)continue;const n=norm(line);if(n.includes('נרשמו באפליקציה')){mode='attending';continue}if(n.includes('לא מגיעים')){mode='absent';continue}if(!mode)continue;const name=clean(line);if(!name||/^(מיקום|שעת|ציוד|אימון)/.test(name))continue;const arr=mode==='attending'?attending:absent;if(!arr.some(x=>norm(x)===norm(name)))arr.push(name)}return {attending,absent,raw:text}}
  function statusOf(name){const d=getSelected(),n=norm(name);if(d.absent.some(x=>norm(x)===n))return 'absent';if(d.attending.some(x=>norm(x)===n))return 'attending';return 'unknown'}
  window.combatAttendanceStatus=statusOf;
  function assignedGearByPerson(){const map={};const equipment=selectedInfo().equipment||[];equipment.forEach(eq=>(eq.assignments||[]).forEach(a=>{const name=clean(a.name);if(!name)return;const key=norm(name);if(!map[key])map[key]={name,gear:[]};const qty=Array.isArray(a.units)&&a.units.length?a.units.length:Number(a.qty||0);const existing=map[key].gear.find(g=>g.key===(eq.id||eq.name));if(existing)existing.qty+=qty;else map[key].gear.push({key:eq.id||eq.name,name:eq.name,qty})}));return map}
  function noShowsWithGear(){const d=getSelected(),map=assignedGearByPerson();return d.absent.map(n=>map[norm(n)]).filter(Boolean)}
  function renderWorkoutSelect(){const select=document.getElementById('attendanceWorkout');if(!select)return;const opts=workoutOptions();if(!opts.some(x=>x.key===selectedWorkout))selectedWorkout='current';const wanted=opts.map(x=>`${x.key}|${x.label}`).join('\n');if(select.dataset.options!==wanted){select.innerHTML=opts.map(x=>`<option value="${esc(x.key)}">${esc(x.label)}</option>`).join('');select.dataset.options=wanted}if(select.value!==selectedWorkout)select.value=selectedWorkout}
  function buildUI(){const tabs=document.querySelector('.tabs'),main=document.querySelector('main');if(!tabs||!main||document.getElementById('attendance'))return;tabs.style.gridTemplateColumns='repeat(4,1fr)';const btn=document.createElement('button');btn.className='tab';btn.dataset.tab='attendance';btn.textContent='נוכחות';tabs.appendChild(btn);const sec=document.createElement('section');sec.id='attendance';sec.className='section';sec.innerHTML=`<div class="titleRow"><h2>נוכחות לאימון</h2><span class="hint">בחר אימון קיים</span></div><div class="card attendance-card"><div class="field"><label>בחר אימון</label><select id="attendanceWorkout" class="input attendance-workout"></select></div><textarea id="attendancePaste" class="input attendance-text" placeholder="הדבק כאן את הרשימה המלאה של האימון..."></textarea><div class="attendance-actions"><button id="parseAttendance" class="btn primary">קלוט רשימה</button><button id="clearAttendance" class="btn danger">נקה לאימון הזה</button></div><div id="attendanceResults"></div></div><div id="noShowWarnings"></div>`;main.appendChild(sec);renderWorkoutSelect();const sel=document.getElementById('attendanceWorkout');sel.onchange=()=>{selectedWorkout=sel.value||'current';const ta=document.getElementById('attendancePaste');if(ta)ta.value='';renderAttendance();decorateTraineeChoices()};btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));btn.classList.add('active');sec.classList.add('active');renderWorkoutSelect();renderAttendance()};document.getElementById('parseAttendance').onclick=()=>{const text=document.getElementById('attendancePaste').value.trim();if(!text)return alert('יש להדביק קודם את רשימת האימון');const d=parseList(text);if(!d.attending.length&&!d.absent.length)return alert('לא הצלחתי לזהות את הרשימות. ודא שיש כותרת "נרשמו באפליקציה" ו-"לא מגיעים".');saveSelected(d)};document.getElementById('clearAttendance').onclick=()=>{if(!confirm(`לנקות את רשימת הנוכחות של ${selectedInfo().label}?`))return;const all=allData();delete all[selectedWorkout];localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));document.getElementById('attendancePaste').value='';renderAttendance()}}
  function renderAttendance(){const root=document.getElementById('attendanceResults');if(!root)return;renderWorkoutSelect();const d=getSelected(),ta=document.getElementById('attendancePaste');if(ta&&!ta.value&&d.raw)ta.value=d.raw;if(!d.attending.length&&!d.absent.length){root.innerHTML='<div class="empty">עדיין לא נקלטה רשימת נוכחות לאימון שנבחר</div>';checkAssignedNoShows();return}const flagged=noShowsWithGear();root.innerHTML=`<div class="attendance-stats single"><div><strong>${flagged.length}</strong><span>לא מגיעים עם ציוד</span></div></div>${flagged.length?'':'<div class="empty">אין באימון הזה אנשים שמסומנים כלא מגיעים ויש אצלם ציוד</div>'}`;checkAssignedNoShows()}
  function allPhones(){try{return JSON.parse(localStorage.getItem(PHONE_KEY)||'{}')}catch{return {}}}
  function normalizePhone(phone){let p=String(phone||'').replace(/[^\d+]/g,'');if(p.startsWith('+'))p=p.slice(1);if(p.startsWith('00'))p=p.slice(2);if(/^0\d{9}$/.test(p))p='972'+p.slice(1);return /^\d{8,15}$/.test(p)?p:''}
  function gearText(person){return (person?.gear||[]).map(g=>`${Number(g.qty||0)} × ${g.name}`).join(' · ')}
  function messageFor(person){return `היי ${person.name}, ראיתי שאתה מסומן כלא מגיע לאימון הקרוב אבל כרגע משויך אליך ${gearText(person)}. תוכל לעדכן אותי לגביהם?`}
  function findPerson(encoded){let name='';try{name=decodeURIComponent(encoded)}catch{name=encoded}return noShowsWithGear().find(p=>norm(p.name)===norm(name))}
  function openWhatsApp(encoded){const person=findPerson(encoded);if(!person)return alert('לא מצאתי את השיוך של המתאמן');const phone=normalizePhone(allPhones()[norm(person.name)]||'');const text=encodeURIComponent(messageFor(person));const url=phone?`https://wa.me/${phone}?text=${text}`:`https://wa.me/?text=${text}`;window.location.href=url}
  async function copyMessage(encoded){const person=findPerson(encoded);if(!person)return alert('לא מצאתי את השיוך של המתאמן');const msg=messageFor(person);try{await navigator.clipboard.writeText(msg);alert('ההודעה הועתקה')}catch{prompt('העתק את ההודעה:',msg)}}
  window.openNoShowWhatsApp=openWhatsApp;
  window.copyNoShowMessage=copyMessage;
  function checkAssignedNoShows(){const box=document.getElementById('noShowWarnings');if(!box)return;const people=noShowsWithGear();const html=people.length?`<div class="titleRow"><h2>⚠️ לא מגיעים עם ציוד</h2><span class="hint">${esc(selectedInfo().label)}</span></div>${people.map(p=>`<div class="card no-show-card"><div class="no-show-info"><strong>${esc(p.name)}</strong><div class="mini">${p.gear.map(g=>`${g.qty} × ${esc(g.name)}`).join(' · ')}</div></div><div class="no-show-actions"><button class="btn small whatsapp-btn" onclick="openNoShowWhatsApp('${encodeURIComponent(p.name)}')">WhatsApp</button><button class="btn small copy-btn" onclick="copyNoShowMessage('${encodeURIComponent(p.name)}')">העתק הודעה</button></div></div>`).join('')}`:'';if(box.innerHTML!==html)box.innerHTML=html}
  function decorateTraineeChoices(){document.querySelectorAll('.trainee-chip').forEach(b=>{let name='';try{name=decodeURIComponent(b.dataset.name||'')}catch{name=b.textContent||''}const absent=statusOf(name)==='absent';const marked=b.classList.contains('trainee-absent');if(absent&&!marked){b.classList.add('trainee-absent');b.title='מסומן כלא מגיע באימון שנבחר';const s=document.createElement('span');s.className='absent-mark';s.textContent=' · לא מגיע';b.appendChild(s)}else if(!absent&&marked){b.classList.remove('trainee-absent');b.title='';b.querySelector('.absent-mark')?.remove()}})}
  let observerBusy=false;const observer=new MutationObserver(()=>{if(observerBusy)return;observerBusy=true;requestAnimationFrame(()=>{decorateTraineeChoices();observerBusy=false})});observer.observe(document.body,{childList:true,subtree:true});
  const saveBtn=document.getElementById('saveAssignment');if(saveBtn){saveBtn.addEventListener('click',e=>{if(selectedWorkout!=='current')return;if(saveBtn.dataset.attendanceConfirmed==='1'){delete saveBtn.dataset.attendanceConfirmed;return}const name=document.getElementById('personName')?.value.trim();if(name&&statusOf(name)==='absent'){e.preventDefault();e.stopImmediatePropagation();if(confirm(`${name} מסומן כלא מגיע לאימון הנוכחי. בכל זאת לשייך לו ציוד?`)){saveBtn.dataset.attendanceConfirmed='1';saveBtn.click()}}},true)}
  const style=document.createElement('style');style.textContent='.attendance-card{padding:14px}.attendance-workout{appearance:auto}.attendance-text{min-height:180px;resize:vertical;line-height:1.55}.attendance-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.attendance-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.attendance-stats.single{grid-template-columns:1fr}.attendance-stats>div{text-align:center;border:1px solid #46513f;border-radius:12px;padding:10px;background:#151a13}.attendance-stats strong{display:block;font-size:22px}.attendance-stats span{font-size:11px;color:#b8baaf}.no-show-card{padding:12px 14px;display:flex;justify-content:space-between;align-items:center;gap:12px;border-color:#74423d}.no-show-info{min-width:0;flex:1}.no-show-actions{display:flex;flex-direction:column;gap:6px;min-width:112px}.whatsapp-btn{background:#183d28;border-color:#2c7a4b;color:#d9ffe7}.copy-btn{background:#242b22;border-color:#56604f;color:#f4f2e8}.trainee-chip.trainee-absent{border-color:#a35249;color:#ffd3ce;background:#321d1b}.absent-mark{font-size:10px;color:#ff9f95}.app-version-fixed{font-size:11px;font-weight:800;color:#aeb3a8;vertical-align:middle;margin-right:6px;white-space:nowrap}@media(max-width:520px){.tabs{gap:5px}.tab{font-size:12px;padding:6px}.attendance-actions{grid-template-columns:1fr}.no-show-card{align-items:stretch;flex-direction:column}.no-show-actions{width:100%;display:grid;grid-template-columns:1fr}.no-show-actions .btn{width:100%}}';document.head.appendChild(style);
  buildUI();renderAttendance();decorateTraineeChoices();document.querySelectorAll('.app-version,.app-version-fixed').forEach(el=>el.remove());const appTitle=document.querySelector('.headline h1');if(appTitle){const version=document.createElement('span');version.className='app-version-fixed';version.dir='ltr';version.textContent='v1.3.6';appTitle.append(' ',version)}
})();