// Workout attendance manager: choose an existing workout, paste attendance, and show only no-shows who have gear.
(function(){
  const ATTENDANCE_KEY='combatEquipmentAttendanceV2';
  const clean=s=>String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').replace(/[*.]/g,'').replace(/^\s*\d+[.)]?\s*/,'').replace(/^\s*[⁠•\-–—]+\s*/,'').trim();
  const norm=s=>clean(s).replace(/\s+/g,' ').toLocaleLowerCase('he');
  let selectedWorkout='current';
  function historyItems(){try{return typeof histories==='function'?histories():JSON.parse(localStorage.getItem('combatEquipmentHistoryV1')||'[]')}catch{return []}}
  function workoutOptions(){const h=historyItems();return [{key:'current',label:'האימון הנוכחי',equipment:state?.equipment||[]}].concat(h.map((x,i)=>({key:'history-'+i,label:x.date||`אימון ${i+1}`,equipment:x.equipment||[]})))}
  function selectedInfo(){return workoutOptions().find(x=>x.key===selectedWorkout)||workoutOptions()[0]}
  function allData(){try{return JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'{}')}catch{return {}}}
  function getSelected(){return allData()[selectedWorkout]||{attending:[],absent:[],raw:''}}
  function saveSelected(data){const all=allData();all[selectedWorkout]=data;localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));renderAttendance();checkAssignedNoShows()}
  function parseList(text){const lines=String(text||'').split(/\r?\n/);let mode='';const attending=[],absent=[];for(const raw of lines){const line=clean(raw);if(!line)continue;const n=norm(line);if(n.includes('נרשמו באפליקציה')){mode='attending';continue}if(n.includes('לא מגיעים')){mode='absent';continue}if(!mode)continue;const name=clean(line);if(!name||/^(מיקום|שעת|ציוד|אימון)/.test(name))continue;const arr=mode==='attending'?attending:absent;if(!arr.some(x=>norm(x)===norm(name)))arr.push(name)}return {attending,absent,raw:text}}
  function statusOf(name){const d=getSelected(),n=norm(name);if(d.absent.some(x=>norm(x)===n))return 'absent';if(d.attending.some(x=>norm(x)===n))return 'attending';return 'unknown'}
  window.combatAttendanceStatus=statusOf;
  function assignedGearByPerson(){const map={};const equipment=selectedInfo()?.equipment||[];equipment.forEach(eq=>(eq.assignments||[]).forEach(a=>{const name=clean(a.name);if(!name)return;const key=norm(name);if(!map[key])map[key]={name,gear:[]};map[key].gear.push({name:eq.name,qty:Number(a.qty||0)})}));return map}
  function noShowsWithGear(){const d=getSelected(),map=assignedGearByPerson();return d.absent.map(n=>map[norm(n)]).filter(Boolean)}
  function renderWorkoutSelect(){const select=document.getElementById('attendanceWorkout');if(!select)return;const opts=workoutOptions();if(!opts.some(x=>x.key===selectedWorkout))selectedWorkout='current';select.innerHTML=opts.map(x=>`<option value="${esc(x.key)}" ${x.key===selectedWorkout?'selected':''}>${esc(x.label)}</option>`).join('')}
  function buildUI(){const tabs=document.querySelector('.tabs'),main=document.querySelector('main');if(!tabs||!main||document.getElementById('attendance'))return;tabs.style.gridTemplateColumns='repeat(4,1fr)';const btn=document.createElement('button');btn.className='tab';btn.dataset.tab='attendance';btn.textContent='נוכחות';tabs.appendChild(btn);const sec=document.createElement('section');sec.id='attendance';sec.className='section';sec.innerHTML=`<div class="titleRow"><h2>נוכחות לאימון</h2><span class="hint">בחר אימון קיים</span></div><div class="card attendance-card"><div class="field"><label>בחר אימון</label><select id="attendanceWorkout" class="input attendance-workout"></select></div><textarea id="attendancePaste" class="input attendance-text" placeholder="הדבק כאן את הרשימה המלאה של האימון..."></textarea><div class="attendance-actions"><button id="parseAttendance" class="btn primary">קלוט רשימה</button><button id="clearAttendance" class="btn danger">נקה לאימון הזה</button></div><div id="attendanceResults"></div></div><div id="noShowWarnings"></div>`;main.appendChild(sec);renderWorkoutSelect();const sel=document.getElementById('attendanceWorkout');sel.onchange=()=>{selectedWorkout=sel.value;document.getElementById('attendancePaste').value='';renderAttendance();decorateTraineeChoices()};btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));btn.classList.add('active');sec.classList.add('active');renderWorkoutSelect();renderAttendance()};document.getElementById('parseAttendance').onclick=()=>{const text=document.getElementById('attendancePaste').value.trim();if(!text)return alert('יש להדביק קודם את רשימת האימון');const d=parseList(text);if(!d.attending.length&&!d.absent.length)return alert('לא הצלחתי לזהות את הרשימות. ודא שיש כותרת "נרשמו באפליקציה" ו-"לא מגיעים".');saveSelected(d)};document.getElementById('clearAttendance').onclick=()=>{if(!confirm(`לנקות את רשימת הנוכחות של ${selectedInfo().label}?`))return;const all=allData();delete all[selectedWorkout];localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));document.getElementById('attendancePaste').value='';renderAttendance();checkAssignedNoShows()}}
  function renderAttendance(){const root=document.getElementById('attendanceResults');if(!root)return;renderWorkoutSelect();const d=getSelected(),ta=document.getElementById('attendancePaste');if(ta&&!ta.value&&d.raw)ta.value=d.raw;if(!d.attending.length&&!d.absent.length){root.innerHTML='<div class="empty">עדיין לא נקלטה רשימת נוכחות לאימון שנבחר</div>';checkAssignedNoShows();return}const flagged=noShowsWithGear();root.innerHTML=`<div class="attendance-stats single"><div><strong>${flagged.length}</strong><span>לא מגיעים עם ציוד</span></div></div>${flagged.length?'':'<div class="empty">אין באימון הזה אנשים שמסומנים כלא מגיעים ויש אצלם ציוד</div>'}`;checkAssignedNoShows()}
  async function copyMessage(name){const msg=`היי ${name}, ראיתי שאתה מסומן כלא מגיע ל${selectedInfo().label} אבל כרגע משויך אליך ציוד. תוכל לעדכן אותי לגבי הציוד?`;try{await navigator.clipboard.writeText(msg);alert('ההודעה הועתקה')}catch{prompt('העתק את ההודעה:',msg)}}
  window.copyNoShowMessage=encoded=>copyMessage(decodeURIComponent(encoded));
  function checkAssignedNoShows(){const box=document.getElementById('noShowWarnings');if(!box)return;const people=noShowsWithGear();box.innerHTML=people.length?`<div class="titleRow"><h2>⚠️ לא מגיעים עם ציוד</h2><span class="hint">${esc(selectedInfo().label)}</span></div>${people.map(p=>`<div class="card no-show-card"><div><strong>${esc(p.name)}</strong><div class="mini">${p.gear.map(g=>`${g.qty} × ${esc(g.name)}`).join(' · ')}</div></div><button class="btn small danger" onclick="copyNoShowMessage('${encodeURIComponent(p.name)}')">העתק הודעה</button></div>`).join('')}`:''}
  function decorateTraineeChoices(){document.querySelectorAll('.trainee-chip').forEach(b=>{b.classList.remove('trainee-absent');b.querySelector('.absent-mark')?.remove();const name=decodeURIComponent(b.dataset.name||'');if(statusOf(name)==='absent'){b.classList.add('trainee-absent');b.title='מסומן כלא מגיע באימון שנבחר';const s=document.createElement('span');s.className='absent-mark';s.textContent=' · לא מגיע';b.appendChild(s)}})}
  const observer=new MutationObserver(()=>{decorateTraineeChoices();checkAssignedNoShows()});observer.observe(document.body,{childList:true,subtree:true});
  const saveBtn=document.getElementById('saveAssignment');if(saveBtn){saveBtn.addEventListener('click',e=>{if(selectedWorkout!=='current')return;if(saveBtn.dataset.attendanceConfirmed==='1'){delete saveBtn.dataset.attendanceConfirmed;return}const name=document.getElementById('personName')?.value.trim();if(name&&statusOf(name)==='absent'){e.preventDefault();e.stopImmediatePropagation();if(confirm(`${name} מסומן כלא מגיע לאימון הנוכחי. בכל זאת לשייך לו ציוד?`)){saveBtn.dataset.attendanceConfirmed='1';saveBtn.click()}}},true)}
  const style=document.createElement('style');style.textContent='.attendance-card{padding:14px}.attendance-workout{appearance:auto}.attendance-text{min-height:180px;resize:vertical;line-height:1.55}.attendance-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.attendance-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.attendance-stats.single{grid-template-columns:1fr}.attendance-stats>div{text-align:center;border:1px solid #46513f;border-radius:12px;padding:10px;background:#151a13}.attendance-stats strong{display:block;font-size:22px}.attendance-stats span{font-size:11px;color:#b8baaf}.no-show-card{padding:12px 14px;display:flex;justify-content:space-between;align-items:center;gap:10px;border-color:#74423d}.trainee-chip.trainee-absent{border-color:#a35249;color:#ffd3ce;background:#321d1b}.absent-mark{font-size:10px;color:#ff9f95}.app-version-fixed{font-size:11px;font-weight:800;color:#aeb3a8;vertical-align:middle;margin-right:6px;white-space:nowrap}@media(max-width:520px){.tabs{gap:5px}.tab{font-size:12px;padding:6px}.attendance-actions{grid-template-columns:1fr}}';document.head.appendChild(style);
  buildUI();renderAttendance();decorateTraineeChoices();document.querySelectorAll('.app-version,.app-version-fixed').forEach(el=>el.remove());const appTitle=document.querySelector('.headline h1');if(appTitle){const version=document.createElement('span');version.className='app-version-fixed';version.dir='ltr';version.textContent='v1.3.3';appTitle.append(' ',version)}
})();