// Workout attendance manager: paste registration list, track attending/not attending, and warn about gear assigned to no-shows.
(function(){
  const ATTENDANCE_KEY='combatEquipmentAttendanceV1';
  const clean=s=>String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').replace(/[*.]/g,'').replace(/^\s*\d+[.)]?\s*/,'').replace(/^\s*[⁠•\-–—]+\s*/,'').trim();
  const norm=s=>clean(s).replace(/\s+/g,' ').toLocaleLowerCase('he');
  const todayKey=()=>new Date().toISOString().slice(0,10);
  function allData(){try{return JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'{}')}catch{return {}}}
  function getToday(){return allData()[todayKey()]||{attending:[],absent:[],raw:''}}
  function saveToday(data){const all=allData();all[todayKey()]=data;localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));renderAttendance();checkAssignedNoShows()}
  function parseList(text){
    const lines=String(text||'').split(/\r?\n/);let mode='';const attending=[],absent=[];
    for(const raw of lines){const line=clean(raw);if(!line)continue;const n=norm(line);
      if(n.includes('נרשמו באפליקציה')){mode='attending';continue}
      if(n.includes('לא מגיעים')){mode='absent';continue}
      if(!mode)continue;
      const name=clean(line);if(!name||/^(מיקום|שעת|ציוד|אימון)/.test(name))continue;
      const arr=mode==='attending'?attending:absent;if(!arr.some(x=>norm(x)===norm(name)))arr.push(name);
    }
    return {attending,absent,raw:text};
  }
  function statusOf(name){const d=getToday(),n=norm(name);if(d.absent.some(x=>norm(x)===n))return 'absent';if(d.attending.some(x=>norm(x)===n))return 'attending';return 'unknown'}
  window.combatAttendanceStatus=statusOf;
  function buildUI(){
    const tabs=document.querySelector('.tabs'),main=document.querySelector('main');if(!tabs||!main||document.getElementById('attendance'))return;
    tabs.style.gridTemplateColumns='repeat(4,1fr)';
    const btn=document.createElement('button');btn.className='tab';btn.dataset.tab='attendance';btn.textContent='נוכחות';tabs.appendChild(btn);
    const sec=document.createElement('section');sec.id='attendance';sec.className='section';sec.innerHTML=`<div class="titleRow"><h2>נוכחות לאימון</h2><span class="hint">הדבק את הודעת האימון</span></div><div class="card attendance-card"><textarea id="attendancePaste" class="input attendance-text" placeholder="הדבק כאן את הרשימה המלאה של האימון..."></textarea><div class="attendance-actions"><button id="parseAttendance" class="btn primary">קלוט רשימה</button><button id="clearAttendance" class="btn danger">נקה להיום</button></div><div id="attendanceResults"></div></div><div id="noShowWarnings"></div>`;main.appendChild(sec);
    btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));btn.classList.add('active');sec.classList.add('active');renderAttendance()};
    document.getElementById('parseAttendance').onclick=()=>{const text=document.getElementById('attendancePaste').value.trim();if(!text)return alert('יש להדביק קודם את רשימת האימון');const d=parseList(text);if(!d.attending.length&&!d.absent.length)return alert('לא הצלחתי לזהות את הרשימות. ודא שיש כותרת "נרשמו באפליקציה" ו-"לא מגיעים".');saveToday(d)};
    document.getElementById('clearAttendance').onclick=()=>{if(!confirm('לנקות את רשימת הנוכחות של היום?'))return;const all=allData();delete all[todayKey()];localStorage.setItem(ATTENDANCE_KEY,JSON.stringify(all));document.getElementById('attendancePaste').value='';renderAttendance();checkAssignedNoShows()};
  }
  function renderAttendance(){const root=document.getElementById('attendanceResults');if(!root)return;const d=getToday();const ta=document.getElementById('attendancePaste');if(ta&&!ta.value&&d.raw)ta.value=d.raw;if(!d.attending.length&&!d.absent.length){root.innerHTML='<div class="empty">עדיין לא נקלטה רשימת נוכחות להיום</div>';return}root.innerHTML=`<div class="attendance-stats"><div><strong>${d.attending.length}</strong><span>מגיעים</span></div><div><strong>${d.absent.length}</strong><span>לא מגיעים</span></div></div><details class="attendance-group" open><summary>מגיעים (${d.attending.length})</summary><div class="attendance-names">${d.attending.map(n=>`<span class="attendance-name yes">${esc(n)}</span>`).join('')}</div></details><details class="attendance-group"><summary>לא מגיעים (${d.absent.length})</summary><div class="attendance-names">${d.absent.map(n=>`<span class="attendance-name no">${esc(n)}</span>`).join('')}</div></details>`;checkAssignedNoShows()}
  function assignedPeople(){const out=[];(state?.equipment||[]).forEach(eq=>(eq.assignments||[]).forEach(a=>{const name=clean(a.name);if(name&&!out.some(x=>norm(x)===norm(name)))out.push(name)}));return out}
  async function copyMessage(name){const msg=`היי ${name}, ראיתי שאתה מסומן כלא מגיע לאימון היום אבל כרגע משויך אליך ציוד. תוכל לעדכן אותי לגבי הציוד?`;try{await navigator.clipboard.writeText(msg);alert('ההודעה הועתקה')}catch{prompt('העתק את ההודעה:',msg)}}
  window.copyNoShowMessage=encoded=>copyMessage(decodeURIComponent(encoded));
  function checkAssignedNoShows(){const box=document.getElementById('noShowWarnings');if(!box)return;const names=assignedPeople().filter(n=>statusOf(n)==='absent');box.innerHTML=names.length?`<div class="titleRow"><h2>⚠️ ציוד אצל מי שלא מגיע</h2></div>${names.map(n=>`<div class="card no-show-card"><div><strong>${esc(n)}</strong><div class="mini">מסומן כלא מגיע אבל משויך לציוד</div></div><button class="btn small danger" onclick="copyNoShowMessage('${encodeURIComponent(n)}')">העתק הודעה</button></div>`).join('')}`:''}
  function decorateTraineeChoices(){document.querySelectorAll('.trainee-chip').forEach(b=>{const name=decodeURIComponent(b.dataset.name||'');if(statusOf(name)==='absent'){b.classList.add('trainee-absent');b.title='מסומן כלא מגיע';if(!b.querySelector('.absent-mark')){const s=document.createElement('span');s.className='absent-mark';s.textContent=' · לא מגיע';b.appendChild(s)}}})}
  const observer=new MutationObserver(()=>{decorateTraineeChoices();checkAssignedNoShows()});observer.observe(document.body,{childList:true,subtree:true});
  const saveBtn=document.getElementById('saveAssignment');if(saveBtn){saveBtn.addEventListener('click',e=>{if(saveBtn.dataset.attendanceConfirmed==='1'){delete saveBtn.dataset.attendanceConfirmed;return}const name=document.getElementById('personName')?.value.trim();if(name&&statusOf(name)==='absent'){e.preventDefault();e.stopImmediatePropagation();if(confirm(`${name} מסומן כלא מגיע לאימון. בכל זאת לשייך לו ציוד?`)){saveBtn.dataset.attendanceConfirmed='1';saveBtn.click()} }},true)}
  const style=document.createElement('style');style.textContent='.attendance-card{padding:14px}.attendance-text{min-height:180px;resize:vertical;line-height:1.55}.attendance-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.attendance-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.attendance-stats>div{text-align:center;border:1px solid #46513f;border-radius:12px;padding:10px;background:#151a13}.attendance-stats strong{display:block;font-size:22px}.attendance-stats span{font-size:11px;color:#b8baaf}.attendance-group{margin-top:10px;border-top:1px solid #394234;padding-top:10px}.attendance-group summary{font-weight:900;cursor:pointer}.attendance-names{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.attendance-name{border-radius:999px;padding:6px 9px;font-size:12px;border:1px solid #4c5843}.attendance-name.yes{background:#172116}.attendance-name.no{background:#321d1b;border-color:#75423d;color:#ffd3ce}.no-show-card{padding:12px 14px;display:flex;justify-content:space-between;align-items:center;gap:10px;border-color:#74423d}.trainee-chip.trainee-absent{border-color:#a35249;color:#ffd3ce;background:#321d1b}.absent-mark{font-size:10px;color:#ff9f95}.app-version-fixed{font-size:11px;font-weight:800;color:#aeb3a8;vertical-align:middle;margin-right:6px;white-space:nowrap}@media(max-width:520px){.tabs{gap:5px}.tab{font-size:12px;padding:6px}.attendance-actions{grid-template-columns:1fr}}';document.head.appendChild(style);
  buildUI();renderAttendance();decorateTraineeChoices();
  document.querySelectorAll('.app-version,.app-version-fixed').forEach(el=>el.remove());const appTitle=document.querySelector('.headline h1');if(appTitle){const version=document.createElement('span');version.className='app-version-fixed';version.dir='ltr';version.textContent='v1.3.0';appTitle.append(' ',version)}
})();