// Contacts count + unknown attendance follow-up + visible app version.
(function(){
  const CONTACTS_KEY='combatEquipmentContactsV1';
  const PHONE_KEY='combatEquipmentPhonesV1';
  const ATTENDANCE_KEY='combatEquipmentAttendanceV2';
  const TRAINEES_KEY='combatEquipmentTraineesV1';
  const VERSION='v'+(window.COMBAT_APP?.version||'2.1.1');
  const clean=s=>String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').trim().replace(/\s+/g,' ');
  const norm=s=>clean(s).toLocaleLowerCase('he');
  const escHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function savedContactCount(){try{const raw=localStorage.getItem(CONTACTS_KEY);if(raw!==null){const contacts=JSON.parse(raw);return Array.isArray(contacts)?contacts.length:0}const legacy=JSON.parse(localStorage.getItem(PHONE_KEY)||'{}');return legacy&&typeof legacy==='object'&&!Array.isArray(legacy)?Object.keys(legacy).length:0}catch{return 0}}
  function setVersion(){let version=document.querySelector('.app-version-fixed');const title=document.querySelector('.headline h1');if(!title)return;document.querySelectorAll('.app-version').forEach(el=>el.remove());if(!version){version=document.createElement('span');version.className='app-version-fixed';version.dir='ltr';title.append(' ',version)}version.textContent=VERSION}
  function updateContactCount(){const summary=document.querySelector('.contacts-card > summary');if(summary)summary.textContent=`אנשי קשר ל־WhatsApp (${savedContactCount()})`}
  function selectedKey(){return document.getElementById('attendanceWorkout')?.value||'current'}
  function selectedAttendance(){try{const all=JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'{}'),key=selectedKey(),history=typeof histories==='function'?histories():[],index=key.startsWith('history:')?history.findIndex(x=>`history:${x.id}`===key):-1,d=all[key]||(index>=0?all[`history-${index}`]:null)||{};return {attending:Array.isArray(d.attending)?d.attending:[],absent:Array.isArray(d.absent)?d.absent:[]}}catch{return {attending:[],absent:[]}}}
  function selectedEquipment(){const key=selectedKey();if(key==='current')return typeof state!=='undefined'&&Array.isArray(state?.equipment)?state.equipment:[];try{const h=typeof histories==='function'?histories():JSON.parse(localStorage.getItem('combatEquipmentHistoryV1')||'[]'),legacy=key.match(/^history-(\d+)$/),item=legacy?h[Number(legacy[1])]:h.find(x=>`history:${x.id}`===key);return Array.isArray(item?.equipment)?item.equipment:[]}catch{return []}}
  function savedTrainees(){try{const raw=JSON.parse(localStorage.getItem(TRAINEES_KEY)||'[]');if(Array.isArray(raw))return raw.map(x=>typeof x==='string'?x:(x?.name||'')).filter(Boolean);if(raw&&Array.isArray(raw.names))return raw.names.filter(Boolean)}catch{}return []}
  function candidates(){const map=new Map();selectedEquipment().forEach(eq=>(eq.assignments||[]).forEach(a=>{const name=clean(a.name);if(name&&!map.has(norm(name)))map.set(norm(name),name)}));if(selectedKey()==='current')savedTrainees().forEach(name=>{name=clean(name);if(name&&!map.has(norm(name)))map.set(norm(name),name)});return [...map.values()]}
  function ambiguousPeople(){const d=selectedAttendance();if(!d.attending.length&&!d.absent.length)return [];const names=[...d.attending,...d.absent],groups=[];for(const shortName of candidates().filter(name=>!norm(name).includes(' '))){const key=norm(shortName);const matches=[...new Map(names.map(name=>[norm(name),name])).values()].filter(name=>{const n=norm(name);return n===key||n.startsWith(key+' ')});if(matches.length>1)groups.push({shortName,matches})}return groups}
  function unknownPeople(){const d=selectedAttendance();if(!d.attending.length&&!d.absent.length)return [];const ambiguous=new Set(ambiguousPeople().map(group=>norm(group.shortName)));const status=window.combatAttendanceStatus;return candidates().filter(name=>!ambiguous.has(norm(name))&&(!status||status(name)==='unknown'))}
  function contactPhone(name){try{const raw=localStorage.getItem(CONTACTS_KEY);if(raw!==null){const list=JSON.parse(raw);if(!Array.isArray(list))return '';const found=list.filter(c=>[c?.name,...(Array.isArray(c?.aliases)?c.aliases:[])].some(a=>norm(a)===norm(name)));return found.length===1?String(found[0].phone||'').replace(/\D/g,''):''}const legacy=JSON.parse(localStorage.getItem(PHONE_KEY)||'{}');const hit=Object.entries(legacy||{}).find(([n])=>norm(n)===norm(name));return hit?String(hit[1]||'').replace(/\D/g,''):''}catch{return ''}}
  function questionMessage(name){return `היי ${name}, רציתי לבדוק אם אתה מגיע לאימון הקרוב?`}
  function openUnknownWhatsApp(name){const phone=contactPhone(name),text=encodeURIComponent(questionMessage(name));window.location.href=phone?`https://wa.me/${phone}?text=${text}`:`https://wa.me/?text=${text}`}
  async function copyUnknownMessage(name){const msg=questionMessage(name);try{await navigator.clipboard.writeText(msg);alert('ההודעה הועתקה')}catch{prompt('העתק את ההודעה:',msg)}}
  let rendering=false;
  function decorateUnknownChips(people=unknownPeople(),ambiguous=ambiguousPeople()){const unknownSet=new Set(people.map(norm)),ambiguousSet=new Set(ambiguous.map(group=>norm(group.shortName)));document.querySelectorAll('.trainee-chip').forEach(chip=>{let name='';try{name=decodeURIComponent(chip.dataset.name||'')}catch{name=chip.textContent||''}const key=norm(name),unknown=unknownSet.has(key),isAmbiguous=ambiguousSet.has(key),unknownMark=chip.querySelector('.unknown-mark'),ambiguousMark=chip.querySelector('.ambiguous-mark');chip.classList.toggle('trainee-unknown',unknown&&!isAmbiguous);chip.classList.toggle('trainee-ambiguous',isAmbiguous);if(unknown&&!isAmbiguous&&!unknownMark){const s=document.createElement('span');s.className='unknown-mark';s.textContent=' · ❓';chip.appendChild(s)}else if((!unknown||isAmbiguous)&&unknownMark)unknownMark.remove();if(isAmbiguous&&!ambiguousMark){const s=document.createElement('span');s.className='ambiguous-mark';s.textContent=' · ⚠️ בדיקה';chip.appendChild(s)}else if(!isAmbiguous&&ambiguousMark)ambiguousMark.remove()})}
  function renderUnknown(){if(rendering)return;rendering=true;try{const box=document.getElementById('noShowWarnings');if(!box)return;document.getElementById('unknownAttendanceWarnings')?.remove();document.getElementById('ambiguousAttendanceWarnings')?.remove();const ambiguous=ambiguousPeople(),people=unknownPeople();if(ambiguous.length){const section=document.createElement('div');section.id='ambiguousAttendanceWarnings';section.innerHTML=`<div class="titleRow"><h2>⚠️ שמות שדורשים בדיקה</h2><span class="hint">${ambiguous.length} שמות עמומים</span></div>${ambiguous.map(group=>`<div class="card ambiguous-attendance-card"><div class="ambiguous-attendance-heading"><strong><span class="ambiguous-symbol">⚠️</span> ${escHtml(group.shortName)}</strong><div class="mini">נמצאו כמה מתאמנים בשם הזה — לא משייכים אוטומטית</div></div><ul class="ambiguous-attendance-list">${group.matches.map(name=>{const d=selectedAttendance(),status=d.attending.some(x=>norm(x)===norm(name))?'מגיע':d.absent.some(x=>norm(x)===norm(name))?'לא מגיע':'לא ידוע';return `<li><span class="ambiguous-symbol small">⚠️</span> <b>${escHtml(name)}</b><span class="ambiguous-status">${status}</span><span class="ambiguous-actions"><button class="btn small whatsapp-btn" data-unknown-whatsapp="${escHtml(name)}">WhatsApp</button><button class="btn small copy-btn" data-unknown-copy="${escHtml(name)}">העתק</button></span></li>`}).join('')}</ul></div>`).join('')}`;box.appendChild(section)}if(people.length){const section=document.createElement('div');section.id='unknownAttendanceWarnings';section.innerHTML=`<div class="titleRow"><h2>❓ עדיין לא ידוע אם מגיעים</h2><span class="hint">${people.length} לבדיקה</span></div>${people.map(name=>`<div class="card unknown-attendance-card"><div class="unknown-attendance-info"><strong><span class="unknown-symbol">?</span> ${escHtml(name)}</strong><div class="mini">לא מופיע כמגיע ולא כלא מגיע</div></div><div class="unknown-attendance-actions"><button class="btn small whatsapp-btn" data-unknown-whatsapp="${escHtml(name)}">WhatsApp</button><button class="btn small copy-btn" data-unknown-copy="${escHtml(name)}">העתק הודעה</button></div></div>`).join('')}`;box.appendChild(section)}decorateUnknownChips(people,ambiguous)}finally{rendering=false}}
  function ensureStyle(){if(document.getElementById('unknownAttendanceStyle'))return;const style=document.createElement('style');style.id='unknownAttendanceStyle';style.textContent='.unknown-attendance-card{padding:12px 14px;display:flex;justify-content:space-between;align-items:center;gap:12px;border-color:#7a6938}.unknown-attendance-info{min-width:0;flex:1}.unknown-symbol{display:inline-grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#473d1e;border:1px solid #8f7b38;color:#ffe08b;font-weight:900}.unknown-attendance-actions{display:flex;flex-direction:column;gap:6px;min-width:112px}.trainee-chip.trainee-unknown{border-color:#8f7b38;color:#ffe7a6;background:#332d18}.unknown-mark{font-size:11px;color:#ffd66e;font-weight:900}.ambiguous-attendance-card{padding:13px 14px;border-color:#9a7136;background:#2a2417}.ambiguous-attendance-heading{display:flex;align-items:flex-start;gap:10px;flex-direction:column}.ambiguous-symbol{display:inline-grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#57451d;border:1px solid #c59a48;color:#ffe39a;font-weight:900;font-size:14px}.ambiguous-symbol.small{width:20px;height:20px;font-size:11px;vertical-align:middle}.ambiguous-attendance-list{list-style:none;margin:10px 0 0;padding:0;border-top:1px solid #6e572f}.ambiguous-attendance-list li{display:flex;align-items:center;gap:7px;padding:9px 0;border-bottom:1px solid #6e572f;flex-wrap:wrap}.ambiguous-status{margin-right:auto;color:#ffd18b;font-size:12px;font-weight:800}.ambiguous-actions{display:flex;gap:5px}.ambiguous-actions .btn{min-height:34px;padding:6px 8px;font-size:11px}.trainee-chip.trainee-ambiguous{border-color:#c59a48;color:#ffe5a1;background:#40341b}.ambiguous-mark{font-size:11px;color:#ffd66e;font-weight:900}@media(max-width:520px){.unknown-attendance-card{align-items:stretch;flex-direction:column}.unknown-attendance-actions{width:100%;display:grid;grid-template-columns:1fr}.unknown-attendance-actions .btn{width:100%}.ambiguous-actions{width:100%;display:grid;grid-template-columns:1fr 1fr}.ambiguous-actions .btn{width:100%}}';document.head.appendChild(style)}
  function refresh(){updateContactCount();setVersion();ensureStyle();renderUnknown()}
  function attach(){refresh();document.addEventListener('change',e=>{if(e.target?.id==='attendanceWorkout')setTimeout(renderUnknown,0)});document.addEventListener('click',e=>{const w=e.target.closest('[data-unknown-whatsapp]');if(w){e.preventDefault();openUnknownWhatsApp(w.dataset.unknownWhatsapp);return}const c=e.target.closest('[data-unknown-copy]');if(c){e.preventDefault();copyUnknownMessage(c.dataset.unknownCopy)}if(e.target.closest('#parseAttendance,#clearAttendance'))setTimeout(renderUnknown,30)});window.addEventListener('storage',e=>{if([CONTACTS_KEY,PHONE_KEY,ATTENDANCE_KEY,TRAINEES_KEY,null].includes(e.key))setTimeout(refresh,0)});const root=document.getElementById('attendance')||document.body;let queued=false;new MutationObserver(()=>{if(rendering||queued)return;queued=true;requestAnimationFrame(()=>{queued=false;refresh()})}).observe(root,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach,{once:true});else attach();
})();

