// Tactical equipment illustrations + per-unit trainee assignment
const equipmentIconSvg={
'jerrycan':`<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="#77865f" d="M17 10h27v8h4a5 5 0 0 1 5 5v33H11V18h6zm8 5v10h12V15z"/><path fill="none" stroke="#c5cbb9" stroke-width="3" d="M18 31l28 18M46 31L18 49"/></svg>`,
'stretcher':`<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="11" y="20" width="42" height="24" rx="4" fill="#f07a22"/><path d="M7 16v32M57 16v32M5 17h12M47 17h12M5 47h12M47 47h12" stroke="#d8d9d2" stroke-width="4" stroke-linecap="round"/><path d="M20 25v14M44 25v14" stroke="#944617" stroke-width="3"/></svg>`,
'sandbags':`<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="#a88f64" d="M19 11h26l-4 9c9 8 10 28 1 35H22c-9-7-8-27 1-35z"/><path stroke="#6d5a3e" stroke-width="3" d="M22 20h20M18 36h28"/></svg>`,
'vest-green':`<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="#526d3d" d="M18 10l11 8h6l11-8 8 14-9 7v24H19V31l-9-7z"/><path fill="#26331e" d="M27 18h10l-2 18h-6z"/><path stroke="#879b72" stroke-width="2" d="M20 39h24M20 47h24"/></svg>`,
'vest-black':`<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="#343735" d="M18 10l11 8h6l11-8 8 14-9 7v24H19V31l-9-7z"/><path fill="#0c0d0c" d="M27 18h10l-2 18h-6z"/><path stroke="#666b66" stroke-width="2" d="M20 39h24M20 47h24"/></svg>`,
'light':`<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="#68705f" d="M13 24h24l13 10-13 10H13z"/><rect x="8" y="21" width="10" height="26" rx="3" fill="#343a31"/><path fill="#ffe27a" d="M49 28l13-7v26l-13-7z"/></svg>`,
'anchor':`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="13" r="7" fill="none" stroke="#aeb4aa" stroke-width="5"/><path d="M32 20v31M16 33H8c1 15 12 23 24 23s23-8 24-23h-8M21 47l11 9 11-9" fill="none" stroke="#aeb4aa" stroke-width="5" stroke-linecap="round"/></svg>`};
function unitHolder(eq,index){return eq.assignments.find(a=>Array.isArray(a.units)&&a.units.includes(index))||null}
function shortName(name){return String(name||'').trim().split(/\s+/)[0]||''}
function freeUnitIndexes(eq){const used=new Set(eq.assignments.flatMap(a=>Array.isArray(a.units)?a.units:[]));return Array.from({length:eq.qty},(_,i)=>i).filter(i=>!used.has(i))}
function groupedAssignments(eq){const g={};eq.assignments.forEach(a=>{const name=String(a.name||'').trim();if(!name)return;g[name]=(g[name]||0)+Number(a.qty||0)});return Object.entries(g)}
renderEquipment=function(){document.getElementById('equipmentList').innerHTML=state.equipment.map(eq=>{const c=checked(eq),a=assigned(eq),p=eq.qty?c/eq.qty*100:0,visual=equipmentIconSvg[eq.id]||'<svg viewBox="0 0 64 64"><path fill="#77865f" d="M13 20h38v34H13z"/><path fill="#a8b291" d="M23 12h18v8H23z"/></svg>',people=groupedAssignments(eq);return `<article class="card"><div class="head"><div class="equip"><div class="icon equipment-art">${visual}</div><div><div class="name">${esc(eq.name)}</div><div class="sub">אושרו ${c} מתוך ${eq.qty} · משויכים ${a}</div></div></div><div class="count">${c}/${eq.qty}</div></div><div class="units">${eq.checked.map((v,i)=>{const h=unitHolder(eq,i);return `<button class="unit ${v?'on':''} ${h?'has-person':''}" onclick="toggleUnit('${eq.id}',${i})"><span class="unit-number">${i+1}</span>${h?`<span class="unit-person">${esc(shortName(h.name))}</span>`:(v?'<span class="unit-check">✓</span>':'')}</button>`}).join('')}</div><div class="progress"><i style="width:${p}%"></i></div><div class="actions"><button class="btn primary" onclick="openAssign('${eq.id}')">שיוך למתאמן</button><button class="btn" onclick="changeQty('${eq.id}')">שינוי כמות</button></div>${people.length?`<div class="assigns">${people.map(([name,qty])=>`<div class="assignment"><div class="person">${esc(name)} <span class="person-qty">${qty}</span></div><button class="btn small danger" onclick="removePersonAssignments('${eq.id}','${encodeURIComponent(name)}')">הסר</button></div>`).join('')}</div>`:''}</article>`}).join('')};
window.openAssign=(id,unitIndex=null)=>{const e=state.equipment.find(x=>x.id===id);if(!e)return;const free=freeUnitIndexes(e);if(unitIndex!==null&&!free.includes(unitIndex)){const h=unitHolder(e,unitIndex);if(h&&confirm(`${h.name} רשום על ${e.name} מספר ${unitIndex+1}. להסיר את השיוך?`)){const ai=e.assignments.indexOf(h);h.units=h.units.filter(n=>n!==unitIndex);h.qty=h.units.length;e.checked[unitIndex]=false;if(h.qty<1)e.assignments.splice(ai,1);save()}return}if(!free.length)return alert('כל היחידות כבר משויכות');assignEquipmentId.value=id;assignEquipmentId.dataset.unitIndex=unitIndex===null?'':String(unitIndex);assignTitle.textContent='שיוך · '+e.name+(unitIndex===null?'':` · מספר ${unitIndex+1}`);personName.value='';personQty.value=1;personQty.max=free.length;assignHint.textContent=`פנויות לשיוך: ${free.length}${unitIndex===null?'':` · הבחירה תתחיל ממספר ${unitIndex+1}`}`;assignModal.classList.add('show');personName.focus()};
window.toggleUnit=(id,i)=>openAssign(id,i);
saveAssignment.onclick=()=>{const e=state.equipment.find(x=>x.id===assignEquipmentId.value),name=personName.value.trim(),qty=Number(personQty.value),startRaw=assignEquipmentId.dataset.unitIndex,start=startRaw===''?null:Number(startRaw),free=freeUnitIndexes(e);if(!name)return alert('יש להזין שם מתאמן');if(!Number.isInteger(qty)||qty<1)return alert('יש להזין כמות תקינה');if(qty>free.length)return alert(`נותרו רק ${free.length} יחידות פנויות`);let units=[];if(start!==null){if(!free.includes(start))return alert('היחידה שנבחרה כבר משויכת');units.push(start)}for(const i of free){if(units.length>=qty)break;if(i!==start)units.push(i)}if(units.length<qty)return alert('אין מספיק יחידות פנויות');units.forEach(i=>e.checked[i]=true);e.assignments.push({name,qty,units});assignModal.classList.remove('show');assignEquipmentId.dataset.unitIndex='';save()};
window.removePersonAssignments=(id,encodedName)=>{const e=state.equipment.find(x=>x.id===id),name=decodeURIComponent(encodedName);if(!e)return;e.assignments.filter(a=>String(a.name||'').trim()===name).forEach(a=>{if(Array.isArray(a.units))a.units.forEach(n=>{if(n<e.checked.length)e.checked[n]=false})});e.assignments=e.assignments.filter(a=>String(a.name||'').trim()!==name);save()};
window.removeAssign=(id,i)=>{const e=state.equipment.find(x=>x.id===id),a=e.assignments[i];if(a&&Array.isArray(a.units))a.units.forEach(n=>{if(n<e.checked.length)e.checked[n]=false});e.assignments.splice(i,1);save()};
const iconStyle=document.createElement('style');iconStyle.textContent='.equipment-art{font-size:0}.equipment-art svg{width:39px;height:39px;display:block}.unit{min-width:46px;width:auto;height:50px;padding:4px 7px;display:flex;flex-direction:column;align-items:center;justify-content:center;line-height:1.05}.unit-number{font-size:14px;font-weight:900}.unit-person{font-size:9px;max-width:58px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:3px}.unit-check{font-size:10px;margin-top:2px}.unit.has-person{border-color:#ff9a4e;box-shadow:inset 0 0 0 1px rgba(255,154,78,.2)}.person-qty{display:inline-grid;place-items:center;min-width:27px;height:27px;padding:0 7px;margin-right:7px;border-radius:999px;background:#f07a22;color:#17110d;font-weight:900}.app-version-fixed{font-size:11px;font-weight:800;color:#aeb3a8;vertical-align:middle;margin-right:6px;white-space:nowrap}';document.head.appendChild(iconStyle);
document.querySelectorAll('.app-version,.app-version-fixed').forEach(el=>el.remove());
const appTitle=document.querySelector('.headline h1');if(appTitle){const version=document.createElement('span');version.className='app-version-fixed';version.dir='ltr';version.textContent='v1.1.4';appTitle.append(' ',version)}
renderEquipment();