// Smart equipment return center: by trainee or equipment, quick actions, progress, missing-only filter.
(function(){
  const RETURN_KEY='combatEquipmentReturnsV1';
  const ATTENDANCE_KEY='combatEquipmentAttendanceV2';
  const norm=s=>String(s||'').replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069\ufeff]/g,'').trim().replace(/\s+/g,' ').toLocaleLowerCase('he');
  let returnMode=false,view='people',missingOnly=true;
  const read=()=>{try{return JSON.parse(localStorage.getItem(RETURN_KEY)||'{}')}catch{return {}}};
  const write=d=>localStorage.setItem(RETURN_KEY,JSON.stringify(d));
  const slotKey=(eq,i)=>`${eq.id}:${i}`;
  const isBack=(eq,i)=>!!read()[slotKey(eq,i)];
  function setSlots(eq,slots,value){const d=read();slots.forEach(i=>d[slotKey(eq,i)]=!!value);write(d)}
  function total(){return state.equipment.reduce((n,e)=>n+e.qty,0)}
  function returnedEq(eq){let n=0;for(let i=0;i<eq.qty;i++)if(isBack(eq,i))n++;return n}
  function returned(){return state.equipment.reduce((n,e)=>n+returnedEq(e),0)}
  function attendance(){try{return JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'{}').current||{absent:[]}}catch{return {absent:[]}}}
  function absent(name){return (attendance().absent||[]).some(x=>norm(x)===norm(name))}
  function allocation(eq){let cursor=0;const rows=[];(eq.assignments||[]).forEach((a,index)=>{const qty=Math.max(0,Math.min(Number(a.qty||0),eq.qty-cursor));const slots=Array.from({length:qty},(_,j)=>cursor+j);cursor+=qty;rows.push({name:a.name,qty,slots,index})});if(cursor<eq.qty)rows.push({name:'ללא שיוך',qty:eq.qty-cursor,slots:Array.from({length:eq.qty-cursor},(_,j)=>cursor+j),unassigned:true});return rows}
  function peopleGroups(){const map=new Map();state.equipment.forEach(eq=>allocation(eq).forEach(a=>{const k=a.unassigned?'__unassigned__':norm(a.name);if(!map.has(k))map.set(k,{name:a.name,unassigned:a.unassigned,items:[]});map.get(k).items.push({eq,slots:a.slots,qty:a.qty})}));return [...map.values()]}
  function slotsReturned(eq,slots){return slots.filter(i=>isBack(eq,i)).length}
  function missing(){return state.equipment.map(eq=>{const nums=[];for(let i=0;i<eq.qty;i++)if(!isBack(eq,i))nums.push(i+1);return {eq,nums}}).filter(x=>x.nums.length)}
  function allSlots(eq){return Array.from({length:eq.qty},(_,i)=>i)}
  function setAll(value){const d=read();state.equipment.forEach(eq=>allSlots(eq).forEach(i=>d[slotKey(eq,i)]=value));write(d);renderReturns()}
  function stepEq(eq,delta){const slots=allSlots(eq);if(delta>0){const i=slots.find(i=>!isBack(eq,i));if(i!==undefined)setSlots(eq,[i],true)}else{const i=[...slots].reverse().find(i=>isBack(eq,i));if(i!==undefined)setSlots(eq,[i],false)}renderReturns()}
  function ensureUI(){
    if(document.getElementById('returnPanel'))return;
    const check=document.getElementById('check');if(!check)return;
    const panel=document.createElement('div');panel.id='returnPanel';panel.innerHTML=`<div class="return-launch"><button id="returnModeBtn" class="btn">↩️ החזרת ציוד</button></div><div id="returnArea" hidden><div class="return-dashboard"><div class="return-numbers"><div><strong id="returnCount">0/0</strong><span>הוחזרו</span></div><div><strong id="returnMissing">0</strong><span>חסרים</span></div></div><div class="return-progress"><i id="returnProgress"></i></div><div class="return-view-tabs"><button data-return-view="people">👤 לפי מתאמן</button><button data-return-view="gear">🎒 לפי ציוד</button></div><div class="return-tools"><button id="returnMissingOnly" class="btn small">רק מה שחסר</button><button id="returnAllBtn" class="btn small">✓ הכל חזר</button><button id="returnResetBtn" class="btn small danger">איפוס</button></div></div><div id="returnList"></div></div>`;check.insertBefore(panel,document.getElementById('equipmentList'));
    document.getElementById('returnModeBtn').onclick=()=>{returnMode=!returnMode;renderReturns()};
    panel.querySelectorAll('[data-return-view]').forEach(b=>b.onclick=()=>{view=b.dataset.returnView;renderReturns()});
    document.getElementById('returnMissingOnly').onclick=()=>{missingOnly=!missingOnly;renderReturns()};
    document.getElementById('returnAllBtn').onclick=()=>{if(confirm('לסמן את כל הציוד כהוחזר?'))setAll(true)};
    document.getElementById('returnResetBtn').onclick=()=>{if(confirm('לאפס את כל סימוני ההחזרה?'))setAll(false)};
    const style=document.createElement('style');style.textContent=`.return-launch{margin:12px 0}.return-launch>.btn{width:100%;border-color:#7da866}.return-dashboard{background:#171e15;border:1px solid #526a48;border-radius:17px;padding:13px;margin:10px 0}.return-numbers{display:grid;grid-template-columns:1fr 1fr;gap:8px;text-align:center}.return-numbers div{background:#10150f;border-radius:12px;padding:9px}.return-numbers strong{display:block;font-size:24px}.return-numbers span{font-size:11px;color:#b8baaf}.return-progress{height:8px;background:#0c100b;border-radius:999px;overflow:hidden;margin:11px 0}.return-progress i{display:block;height:100%;background:#7da866;transition:width .2s}.return-view-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px}.return-view-tabs button{border:1px solid #52604b;background:#20271d;color:#c8cabc;border-radius:11px;padding:10px;font-weight:900}.return-view-tabs button.active{background:#f07a22;border-color:#f07a22;color:#17110d}.return-tools{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-top:8px}.return-tools .btn{min-height:39px;padding:7px 5px}.return-card{padding:13px}.return-card.done{opacity:.62}.return-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.return-person-name{font-size:18px;font-weight:900}.return-person-card.absent-person{border-color:#b45c35;box-shadow:inset 4px 0 #f07a22}.return-person-status{font-size:11px;color:#ffad6b;font-weight:900;margin-top:3px}.return-person-actions{margin-top:10px}.return-person-actions .btn{width:100%;min-height:40px}.return-item{display:grid;grid-template-columns:1fr auto;align-items:center;gap:8px;border-top:1px solid #364031;padding:10px 0}.return-item:first-of-type{border-top:0}.return-item-main b{display:block}.return-item-main span{font-size:12px;color:#b8baaf}.return-check{min-width:76px;border:1px solid #65705b;border-radius:10px;background:#181d15;color:#ddd;padding:9px 8px;font-weight:900}.return-check.done{background:#527a43;border-color:#78a867;color:white}.return-stepper{display:flex;align-items:center;gap:7px}.return-stepper button{width:40px;height:40px;border:1px solid #65705b;border-radius:10px;background:#181d15;color:white;font-size:20px;font-weight:900}.return-stepper strong{min-width:46px;text-align:center}.absent-warning{border-color:#b45c35!important;box-shadow:inset 4px 0 #f07a22}.absent-label{display:inline-block;margin-top:6px;color:#ffb36e;font-size:12px;font-weight:900}@media(max-width:420px){.return-tools{grid-template-columns:1fr 1fr}.return-tools .danger{grid-column:1/-1}}`;document.head.appendChild(style);
  }
  function renderPeople(){let groups=peopleGroups();if(missingOnly)groups=groups.filter(g=>g.items.some(x=>slotsReturned(x.eq,x.slots)<x.qty));if(!groups.length)return '<div class="card empty">✅ אין ציוד חסר</div>';return groups.map(g=>{const done=g.items.every(x=>slotsReturned(x.eq,x.slots)>=x.qty),isAbs=!g.unassigned&&absent(g.name);return `<div class="card return-card return-person-card ${done?'done':''} ${isAbs?'absent-person':''}"><div class="return-head"><div><div class="return-person-name">${g.unassigned?'📦 ציוד ללא שיוך':esc(g.name)}</div>${isAbs?'<div class="return-person-status">⚠️ מסומן כלא מגיע</div>':''}</div><div class="count">${g.items.reduce((n,x)=>n+slotsReturned(x.eq,x.slots),0)}/${g.items.reduce((n,x)=>n+x.qty,0)}</div></div>${g.items.map((x,i)=>{const r=slotsReturned(x.eq,x.slots),ok=r>=x.qty;return `<div class="return-item"><div class="return-item-main"><b>${esc(x.eq.name)}</b><span>${r}/${x.qty} הוחזרו</span></div><button class="return-check ${ok?'done':''}" data-person-group="${esc(g.unassigned?'__unassigned__':norm(g.name))}" data-person-item="${i}">${ok?'✓ הוחזר':'סמן חזר'}</button></div>`}).join('')}<div class="return-person-actions"><button class="btn ${done?'':'primary'}" data-person-all="${esc(g.unassigned?'__unassigned__':norm(g.name))}">${done?'↩ בטל החזרה':'✓ כל הציוד של '+(g.unassigned?'הקבוצה':esc(g.name))+' חזר'}</button></div></div>`}).join('')}
  function renderGear(){let list=state.equipment;if(missingOnly)list=list.filter(eq=>returnedEq(eq)<eq.qty);if(!list.length)return '<div class="card empty">✅ אין ציוד חסר</div>';return list.map(eq=>{const r=returnedEq(eq),done=r>=eq.qty;return `<div class="card return-card ${done?'done':''}"><div class="return-head"><div><div class="name">${esc(eq.name)}</div><div class="sub">${r}/${eq.qty} הוחזרו</div></div><button class="return-check ${done?'done':''}" data-gear-all="${esc(eq.id)}">${done?'✓ הכל חזר':'סמן הכל'}</button></div><div class="return-item"><div class="return-item-main"><b>${eq.qty-r} עדיין חסרים</b><span>${(eq.assignments||[]).length?'משויך: '+esc((eq.assignments||[]).map(a=>a.name+(absent(a.name)?' ⚠️':'')).join(', ')):'ללא שיוכים'}</span></div><div class="return-stepper"><button data-step="-1" data-eq="${esc(eq.id)}">−</button><strong>${r}/${eq.qty}</strong><button data-step="1" data-eq="${esc(eq.id)}">＋</button></div></div></div>`}).join('')}
  function bindActions(){
    document.querySelectorAll('[data-person-item]').forEach(b=>b.onclick=()=>{const g=peopleGroups().find(x=>(x.unassigned?'__unassigned__':norm(x.name))===b.dataset.personGroup);const item=g?.items[Number(b.dataset.personItem)];if(!item)return;const done=slotsReturned(item.eq,item.slots)>=item.qty;setSlots(item.eq,item.slots,!done);renderReturns()});
    document.querySelectorAll('[data-person-all]').forEach(b=>b.onclick=()=>{const g=peopleGroups().find(x=>(x.unassigned?'__unassigned__':norm(x.name))===b.dataset.personAll);if(!g)return;const done=g.items.every(x=>slotsReturned(x.eq,x.slots)>=x.qty);g.items.forEach(x=>setSlots(x.eq,x.slots,!done));renderReturns()});
    document.querySelectorAll('[data-gear-all]').forEach(b=>b.onclick=()=>{const eq=state.equipment.find(x=>x.id===b.dataset.gearAll);if(!eq)return;setSlots(eq,allSlots(eq),returnedEq(eq)<eq.qty);renderReturns()});
    document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const eq=state.equipment.find(x=>x.id===b.dataset.eq);if(eq)stepEq(eq,Number(b.dataset.step))});
  }
  function renderReturns(){ensureUI();const area=document.getElementById('returnArea'),btn=document.getElementById('returnModeBtn');if(!area)return;area.hidden=!returnMode;btn.textContent=returnMode?'✕ סגור החזרת ציוד':'↩️ החזרת ציוד';const r=returned(),t=total(),m=t-r;document.getElementById('returnCount').textContent=`${r}/${t}`;document.getElementById('returnMissing').textContent=m;document.getElementById('returnMissing').style.color=m?'#ff9b87':'#a8d58e';document.getElementById('returnProgress').style.width=(t?Math.round(r/t*100):100)+'%';document.getElementById('returnMissingOnly').textContent=missingOnly?'✓ רק מה שחסר':'הצג רק חסרים';document.querySelectorAll('[data-return-view]').forEach(b=>b.classList.toggle('active',b.dataset.returnView===view));document.getElementById('returnList').innerHTML=view==='people'?renderPeople():renderGear();bindActions();decorateAbsent()}
  function decorateAbsent(){document.querySelectorAll('.assignment').forEach(row=>{const p=row.querySelector('.person');if(!p)return;const isAbs=absent(p.textContent);row.classList.toggle('absent-warning',isAbs);let tag=row.querySelector('.absent-label');if(isAbs&&!tag){tag=document.createElement('div');tag.className='absent-label';tag.textContent='⚠️ מסומן כלא מגיע';p.parentElement.appendChild(tag)}else if(!isAbs&&tag)tag.remove()})}
  window.combatReturnMissing=missing;window.renderCombatReturns=renderReturns;window.combatOpenReturnMode=()=>{returnMode=true;document.querySelector('[data-tab="check"]')?.click();renderReturns();document.getElementById('returnPanel')?.scrollIntoView({behavior:'smooth',block:'start'})};window.combatConfirmFinish=()=>{const m=missing();if(!m.length)return true;returnMode=true;missingOnly=true;view='people';renderReturns();const lines=m.map(x=>`${x.eq.name}: חסרות ${x.nums.length}`);alert(`⚠️ עדיין חסר ציוד\n\n${lines.join('\n')}\n\nפתחתי עבורך את מסך ההחזרה על "רק מה שחסר".`);setTimeout(()=>document.getElementById('returnPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),50);return false};window.combatResetReturns=()=>localStorage.removeItem(RETURN_KEY);
  ensureUI();renderReturns();window.addEventListener('storage',()=>{renderReturns();decorateAbsent()});document.addEventListener('click',()=>setTimeout(decorateAbsent,0));
})();
